### ISSUE TITLE
Stateless restart of the irc bot (via external proxy or exec-swap)

### ISSUE THREAD

**Issue by pharaun** [pharaun/Karmator#136]
It seems like it would be quite useful to reduce the noise of a bot update/restart by having some sort of proxy that sits in front of the bot that allows you to restart the core without disconnecting and reconnecting.

There's a couple of approach, one such approach is to take the xmonad approach and persist the living-state into a file/cli arg and pass the FD over via an exec-swap, or alternatively having some sort of stateless proxy in the front-end that sits there and does only 1 thing, which is (connect to a network and stream the data over to the bot with a identifier of what network it is).

But the proxy would raise the question of:
1. where is the auth bit handled
2. where is the ping bits handled

**Comment by bwbaugh** [comment]
Probably not what you're looking for here, but a hacky solution might be to
use an IRC bouncer like ZNC.

**Comment by pharaun** [comment]
Haha i didn't know anyone watched my repos!

Anyway, yeah I actually used to use ZNC for the bot before i added in support for channel persistence and that worked well. I did end up having a few issues with ZNC feature-set, and I'm not sure how much control I have over them, on if i can force it back into a "simple proxy mode" or not.

I was hoping to have something a bit more dynamic, ie something that allowed the bot to tell the proxy "please add this server to your proxy list" or "please remove this server" for ex. ZNC doesn't seem to have this capacity, at least without a bunch of supporting "/msg *status <command here>" code.

**Comment by pharaun** [comment]
no longer a issue with slack :)
