### ISSUE TITLE
Feature request: Administrative commands to manage karma entries

### ISSUE THREAD

**Issue by klange** [pharaun/Karmator#16]
Sometimes people accidentally change karma for something they didn't mean to - usually because of typos, sometimes because they simply spelled someone's name wrong. This can lead to an abundance of singular items with +1/-1 (or even 0) karma polluting the database. It would be nice to have some commands, issuable only by authorized users, to remove such erroneous entries.

**Comment by pharaun** [comment]
Hasn't been a issue in practice thanks to the ranking. There is now a maintenance batch for purging certain entities out of the db.
